INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0010-0010-0010-0010-001000100010', 'Anni Collection', 'Italian Coffee & Dining Table Series', 'Bespoke curated lookbook for Anni series.', '/images/mag_cover_volume_10.webp', 'covers/mag_cover_volume_10.webp', '/magazines/volume-10.html', 'pdf/volume-10.html', '2026-06-17', true, 'Living') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0011-0011-0011-0011-001000100010', 'Cassie Collection', 'Coffee Table & Living Series', 'Bespoke curated lookbook for Cassie series.', '/images/mag_cover_volume_11.webp', 'covers/mag_cover_volume_11.webp', '/magazines/volume-11.html', 'pdf/volume-11.html', '2026-06-17', true, 'Living') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0012-0012-0012-0012-001000100010', 'Eco Dining Series', 'Eco Sustainable Dining Series', 'Bespoke curated lookbook for Eco Dining Series.', '/images/mag_cover_volume_12.webp', 'covers/mag_cover_volume_12.webp', '/magazines/volume-12.html', 'pdf/volume-12.html', '2026-06-17', true, 'Dining') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0013-0013-0013-0013-001000100010', 'Eco Dining Luxury Series', 'Eco Sustainable Dining Luxury Series', 'Bespoke curated lookbook for Eco Dining Luxury Series.', '/images/mag_cover_volume_13.webp', 'covers/mag_cover_volume_13.webp', '/magazines/volume-13.html', 'pdf/volume-13.html', '2026-06-17', true, 'Dining') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0014-0014-0014-0014-001000100010', 'Ufan Beds Collection', 'Modern Ufan Beds Series', 'Bespoke curated lookbook for Ufan Beds Series.', '/images/mag_cover_volume_14.webp', 'covers/mag_cover_volume_14.webp', '/magazines/volume-14.html', 'pdf/volume-14.html', '2026-06-17', true, 'Bed') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0015-0015-0015-0015-001000100010', '2026 Dining Catalog', 'Modern Dining Series', 'Bespoke curated lookbook for Modern Dining Series.', '/images/mag_cover_volume_15.webp', 'covers/mag_cover_volume_15.webp', '/magazines/volume-15.html', 'pdf/volume-15.html', '2026-06-17', true, 'Dining') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0016-0016-0016-0016-001000100010', 'Lilyaiji Bedside Table', 'Bespoke Bedside Cabinet Series', 'Bespoke curated lookbook for Lilyaiji Bedside Table series.', '/images/mag_cover_volume_16.webp', 'covers/mag_cover_volume_16.webp', '/magazines/volume-16.html', 'pdf/volume-16.html', '2026-06-17', true, 'Bed') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0017-0017-0017-0017-001000100010', 'Lilyaiji Cabinets', 'Luxury Storage & Credenza Series', 'Bespoke curated lookbook for Lilyaiji Cabinets series.', '/images/mag_cover_volume_17.webp', 'covers/mag_cover_volume_17.webp', '/magazines/volume-17.html', 'pdf/volume-17.html', '2026-06-17', true, 'Living') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0018-0018-0018-0018-001000100010', 'Lilyaiji Designer Cabinet', 'Artisanal Credenza & Accent Cabinets', 'Bespoke curated lookbook for Lilyaiji Designer Cabinet series.', '/images/mag_cover_volume_18.webp', 'covers/mag_cover_volume_18.webp', '/magazines/volume-18.html', 'pdf/volume-18.html', '2026-06-17', true, 'Living') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0019-0019-0019-0019-001000100010', 'Lilyaiji Dresser', 'Bespoke Dressers & Vanity Series', 'Bespoke curated lookbook for Lilyaiji Dresser series.', '/images/mag_cover_volume_19.webp', 'covers/mag_cover_volume_19.webp', '/magazines/volume-19.html', 'pdf/volume-19.html', '2026-06-17', true, 'Bed') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0020-0020-0020-0020-001000100010', 'Lu Bed Collection', 'Modern Luxury Bedstead Series', 'Bespoke curated lookbook for Lu Bed series.', '/images/mag_cover_volume_20.webp', 'covers/mag_cover_volume_20.webp', '/magazines/volume-20.html', 'pdf/volume-20.html', '2026-06-17', true, 'Bed') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0021-0021-0021-0021-001000100010', 'Lu Sofa Collection', 'Contemporary Sofa & Sectional Series', 'Bespoke curated lookbook for Lu Sofa series.', '/images/mag_cover_volume_21.webp', 'covers/mag_cover_volume_21.webp', '/magazines/volume-21.html', 'pdf/volume-21.html', '2026-06-17', true, 'Living') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0022-0022-0022-0022-001000100010', 'Lu Designer Dining', 'Architectural Dining Table & Chair Series', 'Bespoke curated lookbook for Lu Designer Dining series.', '/images/mag_cover_volume_22.webp', 'covers/mag_cover_volume_22.webp', '/magazines/volume-22.html', 'pdf/volume-22.html', '2026-06-17', true, 'Dining') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0023-0023-0023-0023-001000100010', 'Mei Beds Collection', 'Contemporary Luxury Bedsteads', 'Bespoke curated lookbook for Mei Beds series.', '/images/mag_cover_volume_23.webp', 'covers/mag_cover_volume_23.webp', '/magazines/volume-23.html', 'pdf/volume-23.html', '2026-06-17', true, 'Bed') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0024-0024-0024-0024-001000100010', 'Becqi Collection', 'Sculptural Seating & Accent Chairs', 'Bespoke curated lookbook for Becqi series.', '/images/mag_cover_volume_24.webp', 'covers/mag_cover_volume_24.webp', '/magazines/volume-24.html', 'pdf/volume-24.html', '2026-06-17', true, 'Living') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0025-0025-0025-0025-001000100010', 'Mei Chair Collection', 'Contemporary Dining & Armchair Series', 'Bespoke curated lookbook for Mei Chair series.', '/images/mag_cover_volume_25.webp', 'covers/mag_cover_volume_25.webp', '/magazines/volume-25.html', 'pdf/volume-25.html', '2026-06-17', true, 'Living') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0026-0026-0026-0026-001000100010', 'Mei Coffee Table Collection', 'Modern Coffee & Side Table Series', 'Bespoke curated lookbook for Mei Coffee Table series.', '/images/mag_cover_volume_26.webp', 'covers/mag_cover_volume_26.webp', '/magazines/volume-26.html', 'pdf/volume-26.html', '2026-06-17', true, 'Living') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0027-0027-0027-0027-001000100010', 'Michale Designer Living Room Chair Series', 'Artisanal Living Room Seating', 'Bespoke curated lookbook for Michale Designer Living Room Chair series.', '/images/mag_cover_volume_27.webp', 'covers/mag_cover_volume_27.webp', '/magazines/volume-27.html', 'pdf/volume-27.html', '2026-06-17', true, 'Living') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0028-0028-0028-0028-001000100010', 'Wine Cabinets Route', 'Exclusive Wine Storage & Bar Cabinets', 'Bespoke curated lookbook for Wine Cabinets Route series.', '/images/mag_cover_volume_28.webp', 'covers/mag_cover_volume_28.webp', '/magazines/volume-28.html', 'pdf/volume-28.html', '2026-06-17', true, 'Living') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0029-0029-0029-0029-001000100010', 'Cabinets Collection', 'Luxury Storage & Credenza Catalog', 'Bespoke curated lookbook for Cabinets series.', '/images/mag_cover_volume_29.webp', 'covers/mag_cover_volume_29.webp', '/magazines/volume-29.html', 'pdf/volume-29.html', '2026-06-17', true, 'Living') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0030-0030-0030-0030-001000100010', 'Cassie Luxury Bed Catalog', 'Premium Luxury Bedstead Catalog', 'Bespoke curated lookbook for Cassie Luxury Bed series.', '/images/mag_cover_volume_30.webp', 'covers/mag_cover_volume_30.webp', '/magazines/volume-30.html', 'pdf/volume-30.html', '2026-06-17', true, 'Bed') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0031-0031-0031-0031-001000100010', 'Kikiven Collection', 'Bespoke Modern Living Catalog', 'Bespoke curated lookbook for Kikiven series.', '/images/mag_cover_volume_31.webp', 'covers/mag_cover_volume_31.webp', '/magazines/volume-31.html', 'pdf/volume-31.html', '2026-06-17', true, 'Living') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0032-0032-0032-0032-001000100010', 'Accent Chairs Collection', 'Luxury Armchairs & Seating Series', 'Bespoke curated lookbook for Accent Chairs series.', '/images/mag_cover_volume_32.webp', 'covers/mag_cover_volume_32.webp', '/magazines/volume-32.html', 'pdf/volume-32.html', '2026-06-17', true, 'Living') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0033-0033-0033-0033-001000100010', 'Cassie Bar Chair Collection', 'Luxury Bar Stool & Counter Chair Series', 'Bespoke curated lookbook for Cassie Bar Chair series.', '/images/mag_cover_volume_33.webp', 'covers/mag_cover_volume_33.webp', '/magazines/volume-33.html', 'pdf/volume-33.html', '2026-06-17', true, 'Dining') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0034-0034-0034-0034-001000100010', 'Cassie Leisure Chair Catalog', 'Contemporary Leisure Chair Series', 'Bespoke curated lookbook for Cassie Leisure Chair series.', '/images/mag_cover_volume_34.webp', 'covers/mag_cover_volume_34.webp', '/magazines/volume-34.html', 'pdf/volume-34.html', '2026-06-17', true, 'Living') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0035-0035-0035-0035-001000100010', 'Chairs Collection', 'Modern Armchairs & Dining Seating', 'Bespoke curated lookbook for Chairs series.', '/images/mag_cover_volume_35.webp', 'covers/mag_cover_volume_35.webp', '/magazines/volume-35.html', 'pdf/volume-35.html', '2026-06-17', true, 'Living') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0036-0036-0036-0036-001000100010', 'DR Coffee Table Collection', 'Contemporary Coffee & End Table Series', 'Bespoke curated lookbook for DR Coffee Table series.', '/images/mag_cover_volume_36.webp', 'covers/mag_cover_volume_36.webp', '/magazines/volume-36.html', 'pdf/volume-36.html', '2026-06-17', true, 'Living') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0037-0037-0037-0037-001000100010', 'Luxe Collection', 'Bespoke Furniture Showpiece Catalog', 'Bespoke curated lookbook for Luxe Collection series.', '/images/mag_cover_volume_37.webp', 'covers/mag_cover_volume_37.webp', '/magazines/volume-37.html', 'pdf/volume-37.html', '2026-06-17', true, 'Living') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0038-0038-0038-0038-001000100010', 'Office Furnitures Collection', 'Luxury Executive Desks & Office Seating', 'Bespoke curated lookbook for Office Furnitures series.', '/images/mag_cover_volume_38.webp', 'covers/mag_cover_volume_38.webp', '/magazines/volume-38.html', 'pdf/volume-38.html', '2026-06-17', true, 'Office') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0039-0039-0039-0039-001000100010', 'Paiyi Collection', 'Exclusive Sculptural Furnishings', 'Bespoke curated lookbook for Paiyi series.', '/images/mag_cover_volume_39.webp', 'covers/mag_cover_volume_39.webp', '/magazines/volume-39.html', 'pdf/volume-39.html', '2026-06-17', true, 'Living') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0040-0040-0040-0040-001000100010', 'Dining Collection', 'Premium Dining Table & Seating Series', 'Bespoke curated lookbook for Dining series.', '/images/mag_cover_volume_40.webp', 'covers/mag_cover_volume_40.webp', '/magazines/volume-40.html', 'pdf/volume-40.html', '2026-06-17', true, 'Dining') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0041-0041-0041-0041-001000100010', 'Aura Canada Lighting', 'Exclusive Architectural Lighting Series', 'Bespoke curated lookbook for Aura Canada series.', '/images/mag_cover_volume_41.webp', 'covers/mag_cover_volume_41.webp', '/magazines/volume-41.html', 'pdf/volume-41.html', '2026-06-17', true, 'Lighting') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0042-0042-0042-0042-001000100010', 'Halo Series Canada Lighting', 'Exclusive Halo Pendant & Spotlight Series', 'Bespoke curated lookbook for Halo Series Canada series.', '/images/mag_cover_volume_42.webp', 'covers/mag_cover_volume_42.webp', '/magazines/volume-42.html', 'pdf/volume-42.html', '2026-06-17', true, 'Lighting') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0043-0043-0043-0043-001000100010', 'Chen Lg Lighting', 'Contemporary Designer Lighting Catalog', 'Bespoke curated lookbook for Chen Lg series.', '/images/mag_cover_volume_43.webp', 'covers/mag_cover_volume_43.webp', '/magazines/volume-43.html', 'pdf/volume-43.html', '2026-06-17', true, 'Lighting') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0044-0044-0044-0044-001000100010', 'Daisy Ed900 Selections', 'Premium Luxury Chandelier Catalog', 'Bespoke curated lookbook for Daisy Ed900 Selections series.', '/images/mag_cover_volume_44.webp', 'covers/mag_cover_volume_44.webp', '/magazines/volume-44.html', 'pdf/volume-44.html', '2026-06-17', true, 'Lighting') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0045-0045-0045-0045-001000100010', 'Jenn I Lighting', 'Bespoke Luxury Pendant Series', 'Bespoke curated lookbook for Jenn I series.', '/images/mag_cover_volume_45.webp', 'covers/mag_cover_volume_45.webp', '/magazines/volume-45.html', 'pdf/volume-45.html', '2026-06-17', true, 'Lighting') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0046-0046-0046-0046-001000100010', 'Jenn Ii Lighting', 'Exclusive Pendant & Table Light Series', 'Bespoke curated lookbook for Jenn Ii series.', '/images/mag_cover_volume_46.webp', 'covers/mag_cover_volume_46.webp', '/magazines/volume-46.html', 'pdf/volume-46.html', '2026-06-17', true, 'Lighting') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0047-0047-0047-0047-001000100010', 'Mili Outdoor Lighting', 'Exclusive Outdoor & Landscape Light Series', 'Bespoke curated lookbook for Mili Outdoor series.', '/images/mag_cover_volume_47.webp', 'covers/mag_cover_volume_47.webp', '/magazines/volume-47.html', 'pdf/volume-47.html', '2026-06-17', true, 'Lighting') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0048-0048-0048-0048-001000100010', 'Xana Lighting', 'Modern Sculptural Light Series', 'Bespoke curated lookbook for Xana series.', '/images/mag_cover_volume_48.webp', 'covers/mag_cover_volume_48.webp', '/magazines/volume-48.html', 'pdf/volume-48.html', '2026-06-17', true, 'Lighting') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0049-0049-0049-0049-001000100010', 'Custom Made Rugs', 'Premium Custom Rugs & Textures', 'Bespoke curated lookbook for Custom Made Rugs series.', '/images/mag_cover_volume_49.webp', 'covers/mag_cover_volume_49.webp', '/magazines/volume-49.html', 'pdf/volume-49.html', '2026-06-17', true, 'Decor') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0050-0050-0050-0050-001000100010', 'Designer Carpets', 'Luxury Architectural Floor Carpets', 'Bespoke curated lookbook for Designer Carpets series.', '/images/mag_cover_volume_50.webp', 'covers/mag_cover_volume_50.webp', '/magazines/volume-50.html', 'pdf/volume-50.html', '2026-06-17', true, 'Decor') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0051-0051-0051-0051-001000100010', 'Designer Rugs', 'Bespoke Contemporary Designer Rugs', 'Bespoke curated lookbook for Designer Rugs series.', '/images/mag_cover_volume_51.webp', 'covers/mag_cover_volume_51.webp', '/magazines/volume-51.html', 'pdf/volume-51.html', '2026-06-17', true, 'Decor') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0052-0052-0052-0052-001000100010', 'Acquarium Showcase', 'Bespoke Luxury Aquarium Systems', 'Bespoke curated lookbook for Acquarium series.', '/images/mag_cover_volume_52.webp', 'covers/mag_cover_volume_52.webp', '/magazines/volume-52.html', 'pdf/volume-52.html', '2026-06-17', true, 'Decor') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0053-0053-0053-0053-001000100010', 'Cabinets Series 2', 'Luxury Storage & Wall Cabinets', 'Bespoke curated lookbook for Cabinets series.', '/images/mag_cover_volume_53.webp', 'covers/mag_cover_volume_53.webp', '/magazines/volume-53.html', 'pdf/volume-53.html', '2026-06-17', true, 'Living') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0054-0054-0054-0054-001000100010', 'Lar Artificial Plants Series 1', 'Bespoke Premium Artificial Foliage', 'Bespoke curated lookbook for Lar Artificial Plants Series 1 series.', '/images/mag_cover_volume_54.webp', 'covers/mag_cover_volume_54.webp', '/magazines/volume-54.html', 'pdf/volume-54.html', '2026-06-17', true, 'Decor') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0055-0055-0055-0055-001000100010', 'Lar Artificial Plants Series 7', 'Bespoke Premium Artificial Ficus & Palms', 'Bespoke curated lookbook for Lar Artificial Plants Series 7 series.', '/images/mag_cover_volume_55.webp', 'covers/mag_cover_volume_55.webp', '/magazines/volume-55.html', 'pdf/volume-55.html', '2026-06-17', true, 'Decor') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0056-0056-0056-0056-001000100010', 'Lar Pots Series 2', 'Sculptural Planters & Pots Series', 'Bespoke curated lookbook for Lar Pots Series 2 series.', '/images/mag_cover_volume_56.webp', 'covers/mag_cover_volume_56.webp', '/magazines/volume-56.html', 'pdf/volume-56.html', '2026-06-17', true, 'Decor') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0057-0057-0057-0057-001000100010', 'Lar Water Fountains', 'Architectural Indoor Water Fountains', 'Bespoke curated lookbook for Lar Water Fountains series.', '/images/mag_cover_volume_57.webp', 'covers/mag_cover_volume_57.webp', '/magazines/volume-57.html', 'pdf/volume-57.html', '2026-06-17', true, 'Decor') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;

INSERT INTO magazines (id, title, issue, description, cover_url, cover_path, pdf_url, pdf_path, published_at, is_active, category) VALUES ('d10b0058-0058-0058-0058-001000100010', 'Smart Toilets Collection', 'Contemporary Intelligent Sanitaryware', 'Bespoke curated lookbook for Smart Toilets series.', '/images/mag_cover_volume_58.webp', 'covers/mag_cover_volume_58.webp', '/magazines/volume-58.html', 'pdf/volume-58.html', '2026-06-17', true, 'Decor') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, issue=EXCLUDED.issue, description=EXCLUDED.description, cover_url=EXCLUDED.cover_url, pdf_url=EXCLUDED.pdf_url, category=EXCLUDED.category;
